/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ashwin' at '8/30/16 10:15 AM' with Gradle 2.13
 *
 * @author ashwin, @date 8/30/16 10:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
